name: SVCMute
version: '2.2'
main: net.envexus.svcmute.SVCMute
api-version: '1.20'
folia-supported: true
softdepend:
  - Essentials
  - LiteBans
  - AdvancedBan
  - AdvancedBanX
  - PlaceholderAPI
depend:
  - voicechat
commands:
  adminjoin:
    permission: svca.join
    aliases:
      - svcjoin
  broadcastvoice:
    permission: svca.broadcast
permissions:
  svca.*:
    description: All permissions
    default: op
    children:
      svca.join: true
      svca.broadcast: true